dist: trusty

language: java

jdk:
  - openjdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - gcc-5
      - g++-5

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel_0.4.5-linux-x86_64.deb
  - sha256sum -c conf/bazel_0.4.5-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.4.5-linux-x86_64.deb

script:
  - bazel build //src:pluriproto --verbose_failures
